"""PROTOTYPE (throwaway): pull the Trail out of a tools/capture.py capture into trail.js.

    python prototype/coverage-rendering/extract.py fixtures/raw-2026-09-30.jsonl

Keeps only time, x, y and vehicleState from MQTT location type 1, plus the mower's own
subtotalArea, so nothing that identifies the mower or its owner leaves the raw capture.
"""

import gzip
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
opener = gzip.open if path.suffix == ".gz" else open
points, area = [], 0.0
with opener(path, "rt") as lines:
    for line in lines:
        record = json.loads(line)
        if record["kind"] != "mqtt" or not record["topic"].endswith("/location"):
            continue
        payload = record["payload"] if isinstance(record["payload"], list) else [record["payload"]]
        for p in payload:
            if p.get("type") == 1:
                points.append([p["time"], float(p["postureX"]), float(p["postureY"]), p["vehicleState"]])
            elif p.get("type") == 2:
                area = max(area, float(p["subtotalArea"]))

points.sort()
out = Path(__file__).with_name("trail.js")
out.write_text(
    f"// Generated by extract.py from {path.name}. [time ms, x m, y m, vehicleState]\n"
    f"window.CAPTURE = {json.dumps({'source': path.name, 'reportedArea': area, 'points': points}, separators=(',', ':'))};\n"
)
print(f"{len(points)} points, mower-reported area {area} m2 -> {out}")
